services:
  nginx1:
    image: nginx:1.20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Host(`nginx1.docker.tvoelkner.de`)"
    networks:
      - traefik_web
networks:
  traefik_web:
    external: true