version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    networks:
      - traefik_web
    restart: always
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.peppermint.rule=Host(`peppermint.docker.tvoelkner.de`)"
    networks:
      - traefik_web
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "12345"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'

networks:
  traefik_web:
    external: true

volumes:
 pgdata_live: