services:
  nginx2:
    image: nginx:1.20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`nginx2.docker.tvoelkner.de`)"
    networks:
      - traefik_web
    ports:
      - "5200:80"
networks:
  traefik_web:
    external: true